# _config.yml
theme: jekyll-theme-minimal
title: teehee
description: teehee
highlighter: rouge
theme: minima
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

nav:
	- home: /
	- about: /about
	- contact: /contact
