# _config.yml
title: teehee title
description: teehee description
highlighter: rouge
theme: minima
kramdown:
	math_engine: mathjax
	syntax_highlighter: rouge

nav:
	- home: /
	- about: /about
	- contact: /contact
